name: Deploy application in multi-env

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Manually run this workflow

jobs:
  CLEANING:
    name: Clean ${{ matrix.environment }}
    runs-on: ubuntu-latest
    environment: CLEAN
    strategy:
      matrix:
        environment:
          - TEST
          - QA
          - PROD
    steps:
      - name: Cleaning ${{ matrix.environment }} ftp server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no "shami65i@${{ secrets.FTP_SERVER }}" << 'EOF'
            cd "${{ secrets.FTP_SERVER }}"
            [ "$(basename "$(pwd)")" = "${{ secrets.FTP_SERVER }}" ] && rm -rf ./*
          EOF


  BUILD:
    name: Build code
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - uses: actions/setup-node@master
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # You can specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build with Vite
        run: npm run build # Use the appropriate build script from your package.json

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer update --ignore-platform-reqs

      - name: Prepare .env file
        run: |
          sed -i "s/DB_DATABASE=.*/DB_DATABASE=${DATABASE}/" .env
          sed -i "s/DB_USERNAME=.*/DB_USERNAME=${USERNAME}/" .env
          sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${PASSWORD}/" .env

      - name: Generate key
        run: php artisan key:generate

      - name: Zip Repository
        run: |
          zip -r release.zip .
        working-directory: ${{ github.workspace }}

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release.zip
          retention-days: 10


  DEVELOPMENT:
    name: Deploy in TEST
    runs-on: ubuntu-latest
    environment: TEST
    needs: BUILD
    steps:
      - name: Download ZIP Artifact
        uses: actions/download-artifact@v3
        with:
          name: release
          path: release

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./release
          exclude: |
            **/.git*
            **/.git*/**

  QUALITYANALYSIS:
    name: Deploy in QA
    runs-on: ubuntu-latest
    environment: QA
    needs: DEVELOPMENT
    steps:
      - name: Download ZIP Artifact
        uses: actions/download-artifact@v3
        with:
          name: release
          path: release

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./release
          exclude: |
            **/.git*
            **/.git*/**

  PRODUCTION:
    name: Deploy in PROD
    runs-on: ubuntu-latest
    environment: PROD    
    needs: QUALITYANALYSIS
    steps:
      - name: Download ZIP Artifact
        uses: actions/download-artifact@v3
        with:
          name: release
          path: release

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./release
          exclude: |
            **/.git*
            **/.git*/**

  MIGRATION:
    name: Migration in ${{ matrix.environment }}
    runs-on: ubuntu-latest
    environment: MIGRATE
    needs: ${{ matrix.tasks }}
    strategy:
      matrix:
        tasks:
          - DEVELOPMENT
          - QUALITYANALYSIS
          - PRODUCTION
    steps:
      - name: Migrating the Database in ${{ matrix.environment }}
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no "shami65i@${{ secrets.FTP_SERVER }}" << 'EOF'
            cd "${{ secrets.FTP_SERVER }}"
            php artisan migrate:fresh --force
          EOF

