name: Every 5 Minutes Workflow
on:
  schedule:
    - cron: '*/5 * * * *'  # This schedule runs the action every 5 minutes.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      # Add your custom steps here.
